Demo aquasecurity/setup-trivy#9 issue

diff --git a/.github/workflows/setup-trivy-only-latest.yml b/.github/workflows/setup-trivy-only-latest.yml
--- a/.github/workflows/setup-trivy-only-latest.yml
+++ b/.github/workflows/setup-trivy-only-latest.yml
@@ -36,3 +36,10 @@ jobs:
         with:
           version: ${{ matrix.version }}
           cache: ${{ matrix.caching }}
+
+      - name: Fail if Trivy Installation Script is still present
+        run: |
+          if [ -f "./trivy/contrib/install.sh" ]; then
+            echo "::error::Trivy install.sh still present"
+            exit 1
+          fi
